# This is a basic workflow to help you get started with Actions
#extra task1
name: DEPLOY_VER
env:
  DEPLOY_VER: "flask-deploy-ver-${{ github.sha }}
  YEAR      : "2022"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  First job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the list of files/directories in your github repository.
        run: ls -lah
      
      - name: Print content of your log.txt file.
        run: cat ./Task1/log.txt
        
      - name: Print: “Hello from “your DEPLOY_VER variable’s content” commit”
        run: echo "Hello from ${{ env.DEPLOY_VER }} commit"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
